spring:
  application:
    name: config-server

  #profile
  profiles:
    active: git

  #cloud configuration
  #https://docs.spring.io/spring-cloud-config/reference/server/environment-repository/file-system-backend.html
  cloud:
    config:
      server:
        git:
          uri: https://github.com/venkatchinmay/microservices-configuration.git
          defaultLabel: dev
          tryMasterBranch: false
          search-paths:
           - licensing-service
server:
  port: 8071

encrypt:
  key: fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo

#Enable all Spring Boot Actuator endpoints.
management:
  endpoints:
    web:
      exposure:
        include: "*"