spring:
  application:
    name: config-server

  #profile
  profiles:
    active: vault


  #cloud configuration
  #https://docs.spring.io/spring-cloud-config/reference/server/environment-repository/file-system-backend.html
  cloud:
    config:
      server:
        vault:
          port: 8200
          host: vault
          kvVersion: 2
          authentication: TOKEN
          token: myroot
          scheme: http


server:
  port: 8071

#Enable all Spring Boot Actuator endpoints.
management:
  endpoints:
    web:
      exposure:
        include: "*"